# baseURL = "http://localhost:8080/docs"
baseURL = "https://pranjalworm.github.io"
languageCode = "en-us"
title = "Pranjal Dubey"
theme = "ananke"
publishdir = "./docs"

SectionPagesMenu = "main"
enableRobotsTXT = true

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  description = "Personal website of Pranjal Dubey"
  featured_image = "./images/home.jpg"
  github = "https://github.com/pranjalworm"
  instagram = "https://www.instagram.com/pranjalworm/"
  recent_posts_number = 4